# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :webserver => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
    :memory => "256"
  },
  :elk => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.102',
    :memory => "2048"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      case boxname.to_s
        when "webserver"
          box.vm.network :forwarded_port, guest: 22, host: 3200, id: 'ssh'
        when "elk"
          box.vm.network :forwarded_port, guest: 22, host: 3201, id: 'ssh'
      end

      box.vm.provider :virtualbox do |vb|
        vb.memory = boxconfig[:memory]  
      end 
        
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"
        ansible.verbose = "vvv"
      end
    end
  end
end
