---

- name: Install base packages
  yum:
    name:
      - java-1.8.0-openjdk 
      - nano
      - curl
    state: present

- name: Import ELK repo key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add elasticsearch repo
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install packages
  yum:
    name:
      - elasticsearch
      - logstash
      - kibana
    state: present

- name: Copy configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'elasticsearch.yml', dest: '/etc/elasticsearch/elasticsearch.yml', group: elasticsearch, mode: '0644' }
    - { src: 'kibana.yml', dest: '/etc/kibana/kibana.yml', group: root, mode: '0644'  }
    # - { src: 'syslog-filter.conf', dest: '/etc/logstash/conf.d/02-syslog-filter.conf', group: root, mode: '0644'  }
    # - { src: 'nginx-filter.conf', dest: '/etc/logstash/conf.d/03-nginx-filter.conf', group: root, mode: '0644'  }
  notify:
    - Enable and start services

...