# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "hw07"
  config.vm.provision "shell", path: "provision_watchlog.sh"
  config.vm.provision "shell", path: "provision_httpd.sh"
end
